### ISSUE TITLE
Run Example for ProjectZomboid

### ISSUE THREAD

**Issue by SteindelSE** [ich777/docker-steamcmd-server#18]
On the Readme.md for the ProjectZomboid branch, I noticed that the second volume mount points to the same container folder as the first:

```
	--volume /path/to/steamcmd:/serverdata/steamcmd \
	--volume /path/to/projectzomboid:/serverdata/steamcmd \
```

I assume the bolded one should be something like `--volume /path/to/projectzomboid:/serverdata/serverfiles`

Thoughts?

**Comment by ich777** [comment]
@SteindelSE thank you for the heads up, simple copy/paste mistake.
Will change that ASAP and close the issue afterwards.

**Comment by ich777** [comment]
Thank you again @SteindelSE!
