### ISSUE TITLE
start-server.sh error line 68

### ISSUE THREAD

**Issue by Rocket01666** [ich777/docker-steamcmd-server#25]
the file/folder path does not exist 

Container details
IMAGE	ich777/steamcmd:latest@sha256:4521f3e11558b7b73fd8115a205fcbd4f9191ad82fb802ffbf9cbb4493882187
CMD	
ENTRYPOINT	/opt/scripts/start.sh
ENV	
DATA_DIR	/serverdata
DATA_PERM	770
GAME_ID	346110
GAME_NAME	ARK_Survival_Evolved
GAME_PARAMS	Ragnarok?listen?ServerCrosshair=True?TheMaxStructuresInRange=100
GAME_PORT	7777
GID	100
LANG	en_US.UTF-8
LANGUAGE	en_US:en
LC_ALL	en_US.UTF-8
PASSWRD	
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_DIR	/serverdata/serverfiles
STEAMCMD_DIR	/serverdata/steamcmd
UID	99
UMASK	000
USER	steam
USERNAME	
VALIDATE	
[_ARK_Survival_Evolved_logs.txt](https://github.com/ich777/docker-steamcmd-server/files/8911988/_ARK_Survival_Evolved_logs.txt)

also see attached logs 

container seems to loop on copying files then eventually gives up, any help is appreciated

**Comment by ich777** [comment]
Ah, you are trying to use ARK with the master branch, look at this run example here:
```
docker run --name ARKSurvivalEvolved -d \
	-p 7777-7778:7777-7778/udp -p 27015:27015/udp -p 27020:27020 \
	--env 'GAME_ID=376030' \
	--env 'MAP=TheIsland' \
	--env 'GAME_PARAMS_EXTRA=-server -log' \
	--env 'UID=99' \
	--env 'GID=100' \
	--volume /path/to/steamcmd:/serverdata/steamcmd \
	--volume /path/to/ark-se:/serverdata/serverfiles \
	ich777/steamcmd:arkse
```

You have use the image `ich777/steamcmd:arkse` not the latest branch. Here is the right tree on GitHub for ARK: [Click](https://github.com/ich777/docker-steamcmd-server/tree/arkse)

**Comment by ich777** [comment]
I‘ll close this for now since no response and usage of the wrong container image.

If you need anything or something isn‘t working feel free to open up this issue again.

**Comment by Rocket01666** [comment]
Thanks that worked perfectly, I cant seem to find a reference the list of dockers other than the one on the unraid forum but it doesn't give the alt build?
