### ISSUE TITLE
TeamFortress2 branch, "Out of memory or address space. Texture quality setting may be too high.

### ISSUE THREAD

**Issue by Sanlys** [ich777/docker-steamcmd-server#27]
debug.log:
`----------------------------------------------
CRASH: Sat 18 Jun 2022 03:03:56 AM PDT
Start Line: ./srcds_linux -game tf -debug +sv_pure 1 +randommap +maxplayers 24 +sv_setsteamaccount -console +port 27015
End of Source crash report
----------------------------------------------`
I have set the sv_setsteamaccount, just removed it from the log.

This error only occurs when mounting it to a storage, and also happens with the cm2network/tf2 image. The container only uses ~23 megabytes when this error occurs, and I have 16 gigs installed and over 13 gigabytes left, so that's not the issue. 

![image](https://user-images.githubusercontent.com/49021092/174433050-8f945295-2b49-4e34-8ef1-9229bc6677ab.png)
My configuration, the only thing not showing in the +sv_setsteamaccount variable.

Any thoughts, the share might be too slow? I've tried running it purely off cache (an ssd) and fully without cache, neither has any different effect.

**Comment by Sanlys** [comment]
![image](https://user-images.githubusercontent.com/49021092/174433179-c80b7758-3f4c-4370-93e9-f159f932e5b9.png)
This might also be useful, these are the logs from the docker container. This comes every 10 seconds, when the server restarts.

**Comment by ich777** [comment]
@Sanlys please use the real path to the game files for TeamFortress2 and not the FUSE path `/mnt/user/appdata/…`

If you have the files on the cache drive it is something like: `/mnt/cache/appdata/…`
Also make sure that you have set the appdata share to use cache `Only` or `Prefer` in the Share Settings.

Of you don‘t have the files on the Cache drive the path is something like /mnt/disk3/appdata/…

**Comment by Sanlys** [comment]
![image](https://user-images.githubusercontent.com/49021092/174434872-01b52355-7de0-4c8a-81ae-a9644f5e0bf1.png)
Is this what you meant? I don't believe I have files on the cache drive, but I'm not sure how to see that. When I specify the path like this, I don't think it should use cache though. I still get the same error.

**Comment by Sanlys** [comment]
I noticed it's now using 1.7 gigs of memory, but still gives me the same error, so probably not enough.

**Comment by ich777** [comment]
> I noticed it's now using 1.7 gigs of memory, but still gives me the same error, so probably not enough.

Forget about those error, the server is actually running.

Just look into the Steam Server Browser and you will see that you now can connect.

The crashing happens because this specific game needs the real file path as mentioned above.

I always recommend to use the real file path because this saves CPU usage and causes less overhead.
Also please notice rhat you only need to set the path to the game files to the real file path the SteamCMD path can be left at the FUSE file path.

**Comment by Sanlys** [comment]
It doesn't show up for me and I can't connect with the direct ip either.
The logs say the server is restarting though, it doesn't look like a warning to me. Did I set the real file path wrong?

**Comment by ich777** [comment]
May I ask why you are posting here and not posting on the official support thread on the forums?

I've now tried it and it works just fine: [log.txt](https://github.com/ich777/docker-steamcmd-server/files/8933521/log.txt)

![screenshot](https://user-images.githubusercontent.com/28066518/174437147-3a87ccfc-41c6-45f4-ac52-a9007892d23a.png)


As you can see the server just shows up fine in the Steam Server Browser.

On what Unraid version are you? Please post your Diagnostics.

**Comment by Sanlys** [comment]
My bad, didn't know you had a support thread. I reset back to defaults, and it seems like it has to be stored on cache? That seems weird to me, but it does work. Thanks for your help

**Comment by ich777** [comment]
@Sanlys please also make sure that you‘ve set you `appdata` share to use cache `Only` or `Prefer`.
