### ISSUE TITLE
steamcmd:arkse server pass issue

### ISSUE THREAD

**Issue by Xstar97** [ich777/docker-steamcmd-server#29]
in the start server script it appears that the a password param is hardcoded and its required. -> https://github.com/ich777/docker-steamcmd-server/blob/e692243d582d555f5afab3b96634b3732f9b99a4/scripts/start-server.sh#L72

can `SRV_PWD` be empty or have a validation check if it is or not and append the param in the script otherwise dont?

while passwords are great sometimes not setting a password is ideal for some instances.

i run this on scale, using truecharts repo -> https://github.com/truecharts/charts/tree/master/charts/incubator/arksurvivalevolved

**Comment by ich777** [comment]
Is it not possible to set the variable `SVR_PWD` empty on Scale?

Even if it‘s hard coded you can leave it empty and no password will be set when someone is trying to connect.
I have a few users on Unraid which are using it that way.

**Comment by Xstar97** [comment]
ok thanks for the clarification, we wanted to be sure that it can be set since the param was hardcoded

**Comment by ich777** [comment]
> ok thanks for the clarification, we wanted to be sure that it can be set since the param was hardcoded

I‘ve tested it back then when I created the container that it workis with a empty variable too, otherwise I wouldn‘t have put it in the `README.md`.
Please let me know when something changed, but since I don‘t heard back from anyone who is running the container without a password I assumed that it‘s working.

I don‘t play much these days anymore because I have a lot of containers to maintain nowadays. 😅

Anyways, I wish you Merry Christmas and Happy Holidays.

**Comment by Xstar97** [comment]
> > ok thanks for the clarification, we wanted to be sure that it can be set since the param was hardcoded
> 
> I‘ve tested it back then when I created the container that it workis with a empty variable too, otherwise I wouldn‘t have put it in the `README.md`. Please let me know when something changed, but since I don‘t heard back from anyone who is running the container without a password I assumed that it‘s working.
> 
> I don‘t play much these days anymore because I have a lot of containers to maintain nowadays. 😅
> 
> Anyways, I wish you Merry Christmas and Happy Holidays.

ty you too :)
