### ISSUE TITLE
steamcmd:icarus doesn't boot

### ISSUE THREAD

**Issue by ryanwake** [ich777/docker-steamcmd-server#30]
What's with the `sleep infinity` in start-server.sh in the icarus branch?

[At this line](https://github.com/ich777/docker-steamcmd-server/blob/icarus/scripts/start-server.sh#L91) in start-server.sh. Is it just because this branch isn't completed/tested so it shouldn't be used? I was trying to test it out and it just never boots, because of the sleep.

**Comment by ich777** [comment]
> What's with the `sleep infinity` in start-server.sh in the icarus branch?
> 
> [At this line](https://github.com/ich777/docker-steamcmd-server/blob/icarus/scripts/start-server.sh#L91) in start-server.sh. Is it just because this branch isn't completed/tested so it shouldn't be used? I was trying to test it out and it just never boots, because of the sleep.

Because it is not public and wasn't meant to be pulled or built by someone, sorry I'll delete the branch.

Icarus isn't stable and a lot of issues/problems which need to be fixed by the devs, also please keep in mind that this is not the up-to-date development version that I use.
