### ISSUE TITLE
steamcmd:dontstarve server startup fails when launching without caves

### ISSUE THREAD

**Issue by rednaxet** [ich777/docker-steamcmd-server#31]
Looks like a bad file path is causing files to not get loaded properly in the block for launching without caves:

https://github.com/ich777/docker-steamcmd-server/blob/75453b0238bea7ba58dcd234bc7da3b2d5da5c91/scripts/start-server.sh#L169

should probably be:
`cd ${SERVER_DIR}/bin${X64_PATH}`

to match the path used in the CAVES block

**Comment by ich777** [comment]
@rednaxet thank you for the report!
You are correct, already pushed a fix and rebuilt the container.
