### ISSUE TITLE
Starbound - line 16: Permission Denied

### ISSUE THREAD

**Issue by Stultusaur** [ich777/docker-steamcmd-server#35]
Issue:

Permission Denied error when launching the container.

Notes:
I am using Portainer to manage/create docker containers.

Configuration:
Name:
starbound

Volumes:
Container: /serverdata/steamcmd
Host: /mnt/games/games/steamcmd

Container: /serverdata/serverfiles
Host: /mnt/games/games/starbound

Environment Variables:
GAME_ID=533830
GAME_NAME=ServerStarbound
UID=9990
GID=9992
USERNAME=<REMOVED>
PASSWRD=<REMOVED>
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
DATA_DIR=/serverdata
STEAMCMD_DIR=/serverdata/steamcmd
SERVER_DIR=/serverdata/serverfiles
GAME_PARAMS=template
GAME_PORT=27015
VALIDATE=
UMASK=000
USER=steam
DATA_PERM=770

<details><summary>Full Logs</summary>
<p>
---Ensuring UID: 9990 matches user---

---Ensuring GID: 9992 matches user---

usermod: no changes

---Setting umask to 000---

---Checking for optional scripts---

---No optional script found, continuing---

---Taking ownership of data...---

---Starting...---

SteamCMD not found!

steamcmd.sh

linux32/steamcmd

linux32/steamerrorreporter

linux32/libstdc++.so.6

linux32/crashhandler.so

---Update SteamCMD---

/opt/scripts/start-server.sh: line 16: /serverdata/steamcmd/steamcmd.sh: Permission denied

---Update Server---

/opt/scripts/start-server.sh: line 46: /serverdata/steamcmd/steamcmd.sh: Permission denied

---Prepare Server---

---Starbound server configuration not found, downloading---

---Server ready---

---Start Server---

---Something went wrong with the game download, putting server into sleep mode---
</p>
</details>

**Comment by ich777** [comment]
Are you really sure that the UID `9990` with the GID `9992` has permission to execute scripts in the folder `/mnt/games/games/steamcmd`.

Usually this indicates a permission issue of some sort on the host side because at these stages the container tries to execute the downloaded `steamcmd.sh`

Please make sure that the user has enough rights to execute scripts.

**Comment by Stultusaur** [comment]
Thanks for the response,

I cannot say 100% if this is the issue or not without checking, but I have
a few other docker containers for different games that do work using the
same user.

None of those are SteamCMD games however.

iirc the folder/file permissions are either 775 or 755 (ug=rwx,o=rx or
u=rwx,go=rx)

**Comment by ich777** [comment]
This is really strange…
All my containers work the same and they are running flawlessly on many systems even if these are not Unraid systems.

I would also recommend that you use the run example from the readme for Starbound:

```
docker run --name Starbound -d \
	-p 21025:21025 -p 21025:21025/udp -p 21026:21026 \
	--env 'GAME_ID=533830' \
	--env 'UID=99' \
	--env 'GID=100' \
	--volume /path/to/steamcmd:/serverdata/steamcmd \
	--volume /path/to/starbound:/serverdata/serverfiles \
	ich777/steamcmd:starbound
```

**Comment by Stultusaur** [comment]
Ran it externally from Portainer. Same problem occurred.

Changed the directory permissions 777, (as a test) and still didn't work.

**Comment by Stultusaur** [comment]
Ignore the above comment, this was because by default the game parameters set "template" instead of a blank string, as a result caused this issue.

Thank you for the assistance in resolving, my self inflicted, problems.
