### ISSUE TITLE
Satisfactory - Error! App '1690800' state is 0x202

### ISSUE THREAD

**Issue by Stultusaur** [ich777/docker-steamcmd-server#42]
Issue:
Error! App '1690800' state is 0x202
When attempting to start a Satisfactory dedicated server.

Notes:
I have had other ich777 servers running using the same steamcmd folder,
Attempted to use a different folder, and same issue.

Unsure of the cause,
There was a couple of files generated, so do not think it is a permission issue.

**Comment by ich777** [comment]
Please post your full log output.

On what machine are you using the container?

**Comment by Stultusaur** [comment]
Hey mate 

Can close this issue,
I am an idiot,
wrote the docker run command the run way around for the volume,
So not only was I mounting it in the wrong drive, I was also wasn't setting the container mapped volume correctly.

Resolved.
