### ISSUE TITLE
Satisfactory: UnrealServer executable name has changed

### ISSUE THREAD

**Issue by roope242** [ich777/docker-steamcmd-server#43]
In https://github.com/ich777/docker-steamcmd-server/blob/satisfactory/scripts/start.sh#L28 we get the PID of the server executable, however it looks like since Update 8 when the game updated the engine from unreal4 => unreal5 the server executable has also been renamed.\
We can confirm this by looking at the `ps` output as well as comparing the return codes from `pidof`:

```bash
# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   6932  3492 ?        Ss   10:25   0:00 /bin/bash /opt/scripts/start.sh
root        15  0.0  0.0   7128  3044 ?        S    10:25   0:00 su steam -c /opt/scripts/start-server.sh
steam       16  0.0  0.0   6932  3364 ?        Ss   10:25   0:00 /bin/bash /opt/scripts/start-server.sh
steam       62  9.7  0.3 2588468 442808 ?      Sl   10:26   0:07 ./UnrealServer-Linux-Shipping FactoryGame -log -unattended -multi
# # Command from start.sh
# pidof UE4Server-Linux-Shipping ; echo $?
1
# # Proposed updated command
# pidof UnrealServer-Linux-Shipping ; echo $?
62
0
```

**Comment by ich777** [comment]
> We can confirm this by looking at the `ps` output as well as comparing the return codes from `pidof`:

Ah, yes, completely forgot about the termination handler, pushed a update for the game executable [here](https://github.com/ich777/docker-steamcmd-server/blob/satisfactory/scripts/start-server.sh#L78-L85) a few weeks ago.

Thanks for the report, will push a update shortly.

**Comment by ich777** [comment]
Update pushed, I'll close this for now, if you experience any other issues then please feel free to open up the issue again or create a new one.
