### ISSUE TITLE
PalWorld docker appears to run, but SteamCMD does not appear to start properly

### ISSUE THREAD

**Issue by mastagon** [ich777/docker-steamcmd-server#51]
![image](https://github.com/ich777/docker-steamcmd-server/assets/31123301/e412af21-ab0b-4c96-a2e7-0dc7d63660a2)

Installed on Unraid 6.9.2. Local/remote users cannot join, and the docker does not respond to port tests. Let me know if there's anything else you need to help me figure out what's going on.

**Comment by ich777** [comment]
> Installed on Unraid 6.9.2.

Sorry I don't give support for such an outdated version from Unraid.

> Local/remote users cannot join

Read this [post](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=1356215) on the Unraid forums.


> the docker does not respond to port tests

Read this [post](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=1356338), to be precise the second paragraph on the Unraid forums.


> Let me know if there's anything else you need to help me figure out what's going on.

The server is running and waiting for connections.
