### ISSUE TITLE
Palworld Version 1.4+

### ISSUE THREAD

**Issue by SalazarElite** [ich777/docker-steamcmd-server#55]
We need to find a way to update the server more easily, currently the game is on version 1.4 and the server does not support this version

**Comment by CurtHubb** [comment]
The read me says "Update Notice: Simply restart the container if a newer version of the game is available." however this didn't work for me. I still get a incompatible error.

**Comment by CurtHubb** [comment]
> What you could do is to force a complete repull from all the files is:
> 
> 1. Stop the container
> 2. Delete everything in the `palworld` directory but NOT the `Pal` directory
> 3. Start the container

This worked great, thank you! Also thank you for all the hard work you do!

**Comment by ich777** [comment]
> Also thank you for all the hard work you do!

Thanks really much appreciated! Really hard these days because nobody seems to read nowadays (except for a few people)... :D

**Comment by ich777** [comment]
@SalazarElite can this be closed?

**Comment by SalazarElite** [comment]
yep, ir you want

________________________________

**Comment by ich777** [comment]
> yep, ir you want

Is this now also resolved for you?

**Comment by SalazarElite** [comment]
in fact I made my own workaround, I wasn't updating for anything so I made a workaround for steamCMD to use the updated version of the server
________________________________

**Comment by ich777** [comment]
> in fact I made my own workaround

I don't quiet understand, if you restart the container it will check for updates and download them eventually.

**Comment by SalazarElite** [comment]
This update on restart function is not working as it should, I use a Truenas Scale server based on Linux and for some reason it does not update, but I made a workaround to download the files from Steam and manually send it to my server where the Palworld server is
________________________________
