### ISSUE TITLE
Changing the ini files does not work

### ISSUE THREAD

**Issue by bgalerani94** [ich777/docker-steamcmd-server#56]
Hello, 

I'm trying to change some configs here but it's not working

I'm shutting down my docker, changing the ini file and then restarting the docker again, but it doesn't seem to work.

Any tips about how to fix that??

Thank you

**Comment by ich777** [comment]
- Stop the container
- Edit the file
- Start the container

You changes will be discarded if you just restart the container.

**Comment by bgalerani94** [comment]
Hello,

Yes, sorry. I'm talking about palworld

Still not getting it to work. The file remains with my changes, but still not seeing them in game after starting the container

**Comment by ich777** [comment]
Please give me more information, on what host do you use the container?

What changes did you apply?

This can only be a configuration error since it is working for me and many other people?

**Comment by ich777** [comment]
Any information?

**Comment by ich777** [comment]
Closing due to no further response, @bgalerani94 if you have any further questions feel free to reopen this issue or create a new issue.
