### ISSUE TITLE
PalWorld 1.4+ still cannot be updated so far

### ISSUE THREAD

**Issue by dai-ych** [ich777/docker-steamcmd-server#57]
I installed this server in the Docker store in Unread, but the Palworld server does not update automatically. Previously, I could manually update it by using the command "/serverdata/teamcmd/teamcmd. sh+login anonymous+app_update 2394010 validate+quit". However, after version 1.4, manual updates would prompt "failed to install app 2394010 (Missing file permissions)"
![UGPA68X0`8M}UE ZEV$0BA8](https://github.com/ich777/docker-steamcmd-server/assets/42855020/a555200d-e655-43d2-96f9-bd7b1985edef)

**Comment by dai-ych** [comment]
好像使用你自带的更新没问题了，之前我没有准确的输入steam账号

**Comment by ich777** [comment]
> but the Palworld server does not update automatically

This is a really hard way of doing it, it would be way easier to:

1. Stop the container
2. Delete everything except for the Pal directory
3. Start the container

However, ho do you solve your issue? It seems more like a file permission issue from what I can see...?
