### ISSUE TITLE
75ms ping?

### ISSUE THREAD

**Issue by 825i** [ich777/docker-steamcmd-server#60]
Just curious. Should the ping be so high?

The container deploys flawlessly but the ping is about 75ms on average.

I'm on a gigabit fibre connection and the container is running on my unraid server on the same home network.

Even if it's connecting to the server over WAN it shouldn't be more than about 5-10ms (if that even).

Any reason for the high ping?

**Comment by ich777** [comment]
> Just curious. Should the ping be so high?

About what container are we talking? In this repository are about 90 different game servers.

**Comment by ich777** [comment]
@825i ?

**Comment by ich777** [comment]
I'm closing this due to no further response, feel free to re-open this issue or open up a new issue.
