### ISSUE TITLE
Stormworks Dedicated Server is now deprecated.

### ISSUE THREAD

**Issue by artificialbutter** [ich777/docker-steamcmd-server#61]
The stormworks developers no longer update the steam stormworks dedicated server app (1247090). Would you be able to update the `stormworks` branch to use their server binary they include in the main game package (573090) instead?

![image](https://github.com/ich777/docker-steamcmd-server/assets/59352535/188a4cb9-0250-4438-9f08-0b67c50cad1c)

**Comment by ich777** [comment]
Thanks for the report.
Sadly enough I have to say that I'll then deprecate the container because it's not designed to support that kind of installation.
