### ISSUE TITLE
Palworld v0.2.0.6 server error

### ISSUE THREAD

**Issue by 2691432189** [ich777/docker-steamcmd-server#62]
Hello, after updating Palworld to v0.2.0.6, an error will occur when unraid starts the docker server.

![Snipaste_2024-04-04_13-01-35](https://github.com/ich777/docker-steamcmd-server/assets/44900334/d19e8c8a-fb8a-4ea5-9b1e-fbdf9f05beb3)

**Comment by ich777** [comment]
> Hello, after updating Palworld to v0.2.0.6, an error will occur when unraid starts the docker server.

Please see [this post](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=1399365) on the Unraid forums.

Please update the container itself and it will work again as it should.

**Comment by 2691432189** [comment]
The error is gone, thank you very much!

![image](https://github.com/ich777/docker-steamcmd-server/assets/44900334/16f1800e-16b2-4588-90d0-2a5a75446450)
