### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by Unibrowser-github** [ich777/docker-steamcmd-server#69]
Hello there. I setup DayZ server and it works amazing. My only issue is that it only shows up as a LAN server. I want it to be available to friends so I forwarded ports 2302 and 27016 but it refuses to show up in community servers. Any idea what I'm doing wrong? This is my first game server I've ever setup. 

PS: Also would love a UT2004 server 😃 😊

**Comment by ich777** [comment]
Are you sure that your NAT Reflection (Hair Pin NAT) is working properly?

If it doesn‘t it is normal that you don‘t see it from the LAN, have your friends from outside your LAN tried to see if the server shows up in the community server list?

Please also double check if you forwarded the correct ports woth the correct protocol.

**Comment by Unibrowser-github** [comment]
No I haven't had a friend try it yet as I thought it wasn't accessible, now I see that NAT loop back could have been my issue, meaning it wouldn't show properly for me but it would remotely. Thanks ill give it a go

**Comment by ich777** [comment]
Any update on this?

**Comment by ich777** [comment]
Closing this due to no response.
